// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo

import (
	context "context"
	model "warungku-backend/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockIOrderRepo is an autogenerated mock type for the IOrderRepo type
type MockIOrderRepo struct {
	mock.Mock
}

type MockIOrderRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOrderRepo) EXPECT() *MockIOrderRepo_Expecter {
	return &MockIOrderRepo_Expecter{mock: &_m.Mock}
}

// ExecuteAtomicCheckout provides a mock function with given fields: ctx, merchantID, req
func (_m *MockIOrderRepo) ExecuteAtomicCheckout(ctx context.Context, merchantID uuid.UUID, req model.CheckoutRequest) (*model.CheckoutResult, error) {
	ret := _m.Called(ctx, merchantID, req)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteAtomicCheckout")
	}

	var r0 *model.CheckoutResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CheckoutRequest) (*model.CheckoutResult, error)); ok {
		return rf(ctx, merchantID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CheckoutRequest) *model.CheckoutResult); ok {
		r0 = rf(ctx, merchantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CheckoutResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.CheckoutRequest) error); ok {
		r1 = rf(ctx, merchantID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepo_ExecuteAtomicCheckout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteAtomicCheckout'
type MockIOrderRepo_ExecuteAtomicCheckout_Call struct {
	*mock.Call
}

// ExecuteAtomicCheckout is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - req model.CheckoutRequest
func (_e *MockIOrderRepo_Expecter) ExecuteAtomicCheckout(ctx interface{}, merchantID interface{}, req interface{}) *MockIOrderRepo_ExecuteAtomicCheckout_Call {
	return &MockIOrderRepo_ExecuteAtomicCheckout_Call{Call: _e.mock.On("ExecuteAtomicCheckout", ctx, merchantID, req)}
}

func (_c *MockIOrderRepo_ExecuteAtomicCheckout_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, req model.CheckoutRequest)) *MockIOrderRepo_ExecuteAtomicCheckout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.CheckoutRequest))
	})
	return _c
}

func (_c *MockIOrderRepo_ExecuteAtomicCheckout_Call) Return(_a0 *model.CheckoutResult, _a1 error) *MockIOrderRepo_ExecuteAtomicCheckout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepo_ExecuteAtomicCheckout_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.CheckoutRequest) (*model.CheckoutResult, error)) *MockIOrderRepo_ExecuteAtomicCheckout_Call {
	_c.Call.Return(run)
	return _c
}

// FindRecentOrders provides a mock function with given fields: ctx, merchantID, limit
func (_m *MockIOrderRepo) FindRecentOrders(ctx context.Context, merchantID uuid.UUID, limit int) ([]model.Order, error) {
	ret := _m.Called(ctx, merchantID, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindRecentOrders")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]model.Order, error)); ok {
		return rf(ctx, merchantID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []model.Order); ok {
		r0 = rf(ctx, merchantID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, merchantID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepo_FindRecentOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRecentOrders'
type MockIOrderRepo_FindRecentOrders_Call struct {
	*mock.Call
}

// FindRecentOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - limit int
func (_e *MockIOrderRepo_Expecter) FindRecentOrders(ctx interface{}, merchantID interface{}, limit interface{}) *MockIOrderRepo_FindRecentOrders_Call {
	return &MockIOrderRepo_FindRecentOrders_Call{Call: _e.mock.On("FindRecentOrders", ctx, merchantID, limit)}
}

func (_c *MockIOrderRepo_FindRecentOrders_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, limit int)) *MockIOrderRepo_FindRecentOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockIOrderRepo_FindRecentOrders_Call) Return(_a0 []model.Order, _a1 error) *MockIOrderRepo_FindRecentOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepo_FindRecentOrders_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) ([]model.Order, error)) *MockIOrderRepo_FindRecentOrders_Call {
	_c.Call.Return(run)
	return _c
}

// MapPostgresError provides a mock function with given fields: err
func (_m *MockIOrderRepo) MapPostgresError(err error) error {
	ret := _m.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for MapPostgresError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOrderRepo_MapPostgresError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapPostgresError'
type MockIOrderRepo_MapPostgresError_Call struct {
	*mock.Call
}

// MapPostgresError is a helper method to define mock.On call
//   - err error
func (_e *MockIOrderRepo_Expecter) MapPostgresError(err interface{}) *MockIOrderRepo_MapPostgresError_Call {
	return &MockIOrderRepo_MapPostgresError_Call{Call: _e.mock.On("MapPostgresError", err)}
}

func (_c *MockIOrderRepo_MapPostgresError_Call) Run(run func(err error)) *MockIOrderRepo_MapPostgresError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockIOrderRepo_MapPostgresError_Call) Return(_a0 error) *MockIOrderRepo_MapPostgresError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOrderRepo_MapPostgresError_Call) RunAndReturn(run func(error) error) *MockIOrderRepo_MapPostgresError_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOrderRepo creates a new instance of MockIOrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOrderRepo {
	mock := &MockIOrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
