// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo

import (
	context "context"
	model "warungku-backend/internal/model"

	mock "github.com/stretchr/testify/mock"

	repo "warungku-backend/internal/repo"

	uuid "github.com/google/uuid"
)

// MockIProductRepo is an autogenerated mock type for the IProductRepo type
type MockIProductRepo struct {
	mock.Mock
}

type MockIProductRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIProductRepo) EXPECT() *MockIProductRepo_Expecter {
	return &MockIProductRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, merchantID, req
func (_m *MockIProductRepo) Create(ctx context.Context, merchantID uuid.UUID, req model.CreateProductRequest) (*model.Product, error) {
	ret := _m.Called(ctx, merchantID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreateProductRequest) (*model.Product, error)); ok {
		return rf(ctx, merchantID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreateProductRequest) *model.Product); ok {
		r0 = rf(ctx, merchantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.CreateProductRequest) error); ok {
		r1 = rf(ctx, merchantID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIProductRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIProductRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - req model.CreateProductRequest
func (_e *MockIProductRepo_Expecter) Create(ctx interface{}, merchantID interface{}, req interface{}) *MockIProductRepo_Create_Call {
	return &MockIProductRepo_Create_Call{Call: _e.mock.On("Create", ctx, merchantID, req)}
}

func (_c *MockIProductRepo_Create_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, req model.CreateProductRequest)) *MockIProductRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.CreateProductRequest))
	})
	return _c
}

func (_c *MockIProductRepo_Create_Call) Return(_a0 *model.Product, _a1 error) *MockIProductRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIProductRepo_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.CreateProductRequest) (*model.Product, error)) *MockIProductRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, merchantID, id
func (_m *MockIProductRepo) Delete(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, merchantID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, merchantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, merchantID, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIProductRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIProductRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - id uuid.UUID
func (_e *MockIProductRepo_Expecter) Delete(ctx interface{}, merchantID interface{}, id interface{}) *MockIProductRepo_Delete_Call {
	return &MockIProductRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, merchantID, id)}
}

func (_c *MockIProductRepo_Delete_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID)) *MockIProductRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockIProductRepo_Delete_Call) Return(_a0 bool, _a1 error) *MockIProductRepo_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIProductRepo_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockIProductRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchSalesFrequency provides a mock function with given fields: ctx, merchantID
func (_m *MockIProductRepo) FetchSalesFrequency(ctx context.Context, merchantID uuid.UUID) (map[string]int, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for FetchSalesFrequency")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (map[string]int, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) map[string]int); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIProductRepo_FetchSalesFrequency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchSalesFrequency'
type MockIProductRepo_FetchSalesFrequency_Call struct {
	*mock.Call
}

// FetchSalesFrequency is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
func (_e *MockIProductRepo_Expecter) FetchSalesFrequency(ctx interface{}, merchantID interface{}) *MockIProductRepo_FetchSalesFrequency_Call {
	return &MockIProductRepo_FetchSalesFrequency_Call{Call: _e.mock.On("FetchSalesFrequency", ctx, merchantID)}
}

func (_c *MockIProductRepo_FetchSalesFrequency_Call) Run(run func(ctx context.Context, merchantID uuid.UUID)) *MockIProductRepo_FetchSalesFrequency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIProductRepo_FetchSalesFrequency_Call) Return(_a0 map[string]int, _a1 error) *MockIProductRepo_FetchSalesFrequency_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIProductRepo_FetchSalesFrequency_Call) RunAndReturn(run func(context.Context, uuid.UUID) (map[string]int, error)) *MockIProductRepo_FetchSalesFrequency_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByMerchant provides a mock function with given fields: ctx, merchantID, opts
func (_m *MockIProductRepo) FindAllByMerchant(ctx context.Context, merchantID uuid.UUID, opts repo.FindProductOptions) ([]model.Product, error) {
	ret := _m.Called(ctx, merchantID, opts)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByMerchant")
	}

	var r0 []model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, repo.FindProductOptions) ([]model.Product, error)); ok {
		return rf(ctx, merchantID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, repo.FindProductOptions) []model.Product); ok {
		r0 = rf(ctx, merchantID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, repo.FindProductOptions) error); ok {
		r1 = rf(ctx, merchantID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIProductRepo_FindAllByMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByMerchant'
type MockIProductRepo_FindAllByMerchant_Call struct {
	*mock.Call
}

// FindAllByMerchant is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - opts repo.FindProductOptions
func (_e *MockIProductRepo_Expecter) FindAllByMerchant(ctx interface{}, merchantID interface{}, opts interface{}) *MockIProductRepo_FindAllByMerchant_Call {
	return &MockIProductRepo_FindAllByMerchant_Call{Call: _e.mock.On("FindAllByMerchant", ctx, merchantID, opts)}
}

func (_c *MockIProductRepo_FindAllByMerchant_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, opts repo.FindProductOptions)) *MockIProductRepo_FindAllByMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(repo.FindProductOptions))
	})
	return _c
}

func (_c *MockIProductRepo_FindAllByMerchant_Call) Return(_a0 []model.Product, _a1 error) *MockIProductRepo_FindAllByMerchant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIProductRepo_FindAllByMerchant_Call) RunAndReturn(run func(context.Context, uuid.UUID, repo.FindProductOptions) ([]model.Product, error)) *MockIProductRepo_FindAllByMerchant_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, merchantID, id
func (_m *MockIProductRepo) FindByID(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*model.Product, error) {
	ret := _m.Called(ctx, merchantID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Product, error)); ok {
		return rf(ctx, merchantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Product); ok {
		r0 = rf(ctx, merchantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIProductRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIProductRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - id uuid.UUID
func (_e *MockIProductRepo_Expecter) FindByID(ctx interface{}, merchantID interface{}, id interface{}) *MockIProductRepo_FindByID_Call {
	return &MockIProductRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, merchantID, id)}
}

func (_c *MockIProductRepo_FindByID_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID)) *MockIProductRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockIProductRepo_FindByID_Call) Return(_a0 *model.Product, _a1 error) *MockIProductRepo_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIProductRepo_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Product, error)) *MockIProductRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleActive provides a mock function with given fields: ctx, merchantID, id, isActive
func (_m *MockIProductRepo) ToggleActive(ctx context.Context, merchantID uuid.UUID, id uuid.UUID, isActive bool) (bool, error) {
	ret := _m.Called(ctx, merchantID, id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for ToggleActive")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) (bool, error)); ok {
		return rf(ctx, merchantID, id, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) bool); ok {
		r0 = rf(ctx, merchantID, id, isActive)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, merchantID, id, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIProductRepo_ToggleActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleActive'
type MockIProductRepo_ToggleActive_Call struct {
	*mock.Call
}

// ToggleActive is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - id uuid.UUID
//   - isActive bool
func (_e *MockIProductRepo_Expecter) ToggleActive(ctx interface{}, merchantID interface{}, id interface{}, isActive interface{}) *MockIProductRepo_ToggleActive_Call {
	return &MockIProductRepo_ToggleActive_Call{Call: _e.mock.On("ToggleActive", ctx, merchantID, id, isActive)}
}

func (_c *MockIProductRepo_ToggleActive_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID, isActive bool)) *MockIProductRepo_ToggleActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *MockIProductRepo_ToggleActive_Call) Return(_a0 bool, _a1 error) *MockIProductRepo_ToggleActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIProductRepo_ToggleActive_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, bool) (bool, error)) *MockIProductRepo_ToggleActive_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, merchantID, id, req
func (_m *MockIProductRepo) Update(ctx context.Context, merchantID uuid.UUID, id uuid.UUID, req model.UpdateProductRequest) (*model.Product, error) {
	ret := _m.Called(ctx, merchantID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.UpdateProductRequest) (*model.Product, error)); ok {
		return rf(ctx, merchantID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.UpdateProductRequest) *model.Product); ok {
		r0 = rf(ctx, merchantID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, model.UpdateProductRequest) error); ok {
		r1 = rf(ctx, merchantID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIProductRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIProductRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - id uuid.UUID
//   - req model.UpdateProductRequest
func (_e *MockIProductRepo_Expecter) Update(ctx interface{}, merchantID interface{}, id interface{}, req interface{}) *MockIProductRepo_Update_Call {
	return &MockIProductRepo_Update_Call{Call: _e.mock.On("Update", ctx, merchantID, id, req)}
}

func (_c *MockIProductRepo_Update_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID, req model.UpdateProductRequest)) *MockIProductRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(model.UpdateProductRequest))
	})
	return _c
}

func (_c *MockIProductRepo_Update_Call) Return(_a0 *model.Product, _a1 error) *MockIProductRepo_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIProductRepo_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, model.UpdateProductRequest) (*model.Product, error)) *MockIProductRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIProductRepo creates a new instance of MockIProductRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIProductRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIProductRepo {
	mock := &MockIProductRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
