// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo

import (
	context "context"
	model "warungku-backend/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockIStorefrontRepo is an autogenerated mock type for the IStorefrontRepo type
type MockIStorefrontRepo struct {
	mock.Mock
}

type MockIStorefrontRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStorefrontRepo) EXPECT() *MockIStorefrontRepo_Expecter {
	return &MockIStorefrontRepo_Expecter{mock: &_m.Mock}
}

// CheckSlugAvailable provides a mock function with given fields: ctx, merchantID, slug
func (_m *MockIStorefrontRepo) CheckSlugAvailable(ctx context.Context, merchantID uuid.UUID, slug string) (bool, error) {
	ret := _m.Called(ctx, merchantID, slug)

	if len(ret) == 0 {
		panic("no return value specified for CheckSlugAvailable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return rf(ctx, merchantID, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = rf(ctx, merchantID, slug)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, merchantID, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIStorefrontRepo_CheckSlugAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckSlugAvailable'
type MockIStorefrontRepo_CheckSlugAvailable_Call struct {
	*mock.Call
}

// CheckSlugAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - slug string
func (_e *MockIStorefrontRepo_Expecter) CheckSlugAvailable(ctx interface{}, merchantID interface{}, slug interface{}) *MockIStorefrontRepo_CheckSlugAvailable_Call {
	return &MockIStorefrontRepo_CheckSlugAvailable_Call{Call: _e.mock.On("CheckSlugAvailable", ctx, merchantID, slug)}
}

func (_c *MockIStorefrontRepo_CheckSlugAvailable_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, slug string)) *MockIStorefrontRepo_CheckSlugAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockIStorefrontRepo_CheckSlugAvailable_Call) Return(_a0 bool, _a1 error) *MockIStorefrontRepo_CheckSlugAvailable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIStorefrontRepo_CheckSlugAvailable_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (bool, error)) *MockIStorefrontRepo_CheckSlugAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDefault provides a mock function with given fields: ctx, merchantID, slug, displayName
func (_m *MockIStorefrontRepo) CreateDefault(ctx context.Context, merchantID uuid.UUID, slug string, displayName string) (*model.Storefront, error) {
	ret := _m.Called(ctx, merchantID, slug, displayName)

	if len(ret) == 0 {
		panic("no return value specified for CreateDefault")
	}

	var r0 *model.Storefront
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*model.Storefront, error)); ok {
		return rf(ctx, merchantID, slug, displayName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *model.Storefront); ok {
		r0 = rf(ctx, merchantID, slug, displayName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Storefront)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, merchantID, slug, displayName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIStorefrontRepo_CreateDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDefault'
type MockIStorefrontRepo_CreateDefault_Call struct {
	*mock.Call
}

// CreateDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - slug string
//   - displayName string
func (_e *MockIStorefrontRepo_Expecter) CreateDefault(ctx interface{}, merchantID interface{}, slug interface{}, displayName interface{}) *MockIStorefrontRepo_CreateDefault_Call {
	return &MockIStorefrontRepo_CreateDefault_Call{Call: _e.mock.On("CreateDefault", ctx, merchantID, slug, displayName)}
}

func (_c *MockIStorefrontRepo_CreateDefault_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, slug string, displayName string)) *MockIStorefrontRepo_CreateDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIStorefrontRepo_CreateDefault_Call) Return(_a0 *model.Storefront, _a1 error) *MockIStorefrontRepo_CreateDefault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIStorefrontRepo_CreateDefault_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) (*model.Storefront, error)) *MockIStorefrontRepo_CreateDefault_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOnlineOrder provides a mock function with given fields: ctx, slug, req
func (_m *MockIStorefrontRepo) CreateOnlineOrder(ctx context.Context, slug string, req model.CreateOnlineOrderRequest) (*model.OnlineOrder, error) {
	ret := _m.Called(ctx, slug, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOnlineOrder")
	}

	var r0 *model.OnlineOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CreateOnlineOrderRequest) (*model.OnlineOrder, error)); ok {
		return rf(ctx, slug, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CreateOnlineOrderRequest) *model.OnlineOrder); ok {
		r0 = rf(ctx, slug, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OnlineOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.CreateOnlineOrderRequest) error); ok {
		r1 = rf(ctx, slug, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIStorefrontRepo_CreateOnlineOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOnlineOrder'
type MockIStorefrontRepo_CreateOnlineOrder_Call struct {
	*mock.Call
}

// CreateOnlineOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - req model.CreateOnlineOrderRequest
func (_e *MockIStorefrontRepo_Expecter) CreateOnlineOrder(ctx interface{}, slug interface{}, req interface{}) *MockIStorefrontRepo_CreateOnlineOrder_Call {
	return &MockIStorefrontRepo_CreateOnlineOrder_Call{Call: _e.mock.On("CreateOnlineOrder", ctx, slug, req)}
}

func (_c *MockIStorefrontRepo_CreateOnlineOrder_Call) Run(run func(ctx context.Context, slug string, req model.CreateOnlineOrderRequest)) *MockIStorefrontRepo_CreateOnlineOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CreateOnlineOrderRequest))
	})
	return _c
}

func (_c *MockIStorefrontRepo_CreateOnlineOrder_Call) Return(_a0 *model.OnlineOrder, _a1 error) *MockIStorefrontRepo_CreateOnlineOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIStorefrontRepo_CreateOnlineOrder_Call) RunAndReturn(run func(context.Context, string, model.CreateOnlineOrderRequest) (*model.OnlineOrder, error)) *MockIStorefrontRepo_CreateOnlineOrder_Call {
	_c.Call.Return(run)
	return _c
}

// FindByMerchant provides a mock function with given fields: ctx, merchantID
func (_m *MockIStorefrontRepo) FindByMerchant(ctx context.Context, merchantID uuid.UUID) (*model.Storefront, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for FindByMerchant")
	}

	var r0 *model.Storefront
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Storefront, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Storefront); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Storefront)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIStorefrontRepo_FindByMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByMerchant'
type MockIStorefrontRepo_FindByMerchant_Call struct {
	*mock.Call
}

// FindByMerchant is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
func (_e *MockIStorefrontRepo_Expecter) FindByMerchant(ctx interface{}, merchantID interface{}) *MockIStorefrontRepo_FindByMerchant_Call {
	return &MockIStorefrontRepo_FindByMerchant_Call{Call: _e.mock.On("FindByMerchant", ctx, merchantID)}
}

func (_c *MockIStorefrontRepo_FindByMerchant_Call) Run(run func(ctx context.Context, merchantID uuid.UUID)) *MockIStorefrontRepo_FindByMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIStorefrontRepo_FindByMerchant_Call) Return(_a0 *model.Storefront, _a1 error) *MockIStorefrontRepo_FindByMerchant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIStorefrontRepo_FindByMerchant_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Storefront, error)) *MockIStorefrontRepo_FindByMerchant_Call {
	_c.Call.Return(run)
	return _c
}

// FindLinkedProducts provides a mock function with given fields: ctx, storefrontID
func (_m *MockIStorefrontRepo) FindLinkedProducts(ctx context.Context, storefrontID uuid.UUID) ([]model.StorefrontProduct, error) {
	ret := _m.Called(ctx, storefrontID)

	if len(ret) == 0 {
		panic("no return value specified for FindLinkedProducts")
	}

	var r0 []model.StorefrontProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.StorefrontProduct, error)); ok {
		return rf(ctx, storefrontID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.StorefrontProduct); ok {
		r0 = rf(ctx, storefrontID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.StorefrontProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, storefrontID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIStorefrontRepo_FindLinkedProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLinkedProducts'
type MockIStorefrontRepo_FindLinkedProducts_Call struct {
	*mock.Call
}

// FindLinkedProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - storefrontID uuid.UUID
func (_e *MockIStorefrontRepo_Expecter) FindLinkedProducts(ctx interface{}, storefrontID interface{}) *MockIStorefrontRepo_FindLinkedProducts_Call {
	return &MockIStorefrontRepo_FindLinkedProducts_Call{Call: _e.mock.On("FindLinkedProducts", ctx, storefrontID)}
}

func (_c *MockIStorefrontRepo_FindLinkedProducts_Call) Run(run func(ctx context.Context, storefrontID uuid.UUID)) *MockIStorefrontRepo_FindLinkedProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIStorefrontRepo_FindLinkedProducts_Call) Return(_a0 []model.StorefrontProduct, _a1 error) *MockIStorefrontRepo_FindLinkedProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIStorefrontRepo_FindLinkedProducts_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.StorefrontProduct, error)) *MockIStorefrontRepo_FindLinkedProducts_Call {
	_c.Call.Return(run)
	return _c
}

// FindPublicBySlug provides a mock function with given fields: ctx, slug
func (_m *MockIStorefrontRepo) FindPublicBySlug(ctx context.Context, slug string) (*model.PublicStorefrontCatalog, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindPublicBySlug")
	}

	var r0 *model.PublicStorefrontCatalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.PublicStorefrontCatalog, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.PublicStorefrontCatalog); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PublicStorefrontCatalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIStorefrontRepo_FindPublicBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPublicBySlug'
type MockIStorefrontRepo_FindPublicBySlug_Call struct {
	*mock.Call
}

// FindPublicBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockIStorefrontRepo_Expecter) FindPublicBySlug(ctx interface{}, slug interface{}) *MockIStorefrontRepo_FindPublicBySlug_Call {
	return &MockIStorefrontRepo_FindPublicBySlug_Call{Call: _e.mock.On("FindPublicBySlug", ctx, slug)}
}

func (_c *MockIStorefrontRepo_FindPublicBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockIStorefrontRepo_FindPublicBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIStorefrontRepo_FindPublicBySlug_Call) Return(_a0 *model.PublicStorefrontCatalog, _a1 error) *MockIStorefrontRepo_FindPublicBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIStorefrontRepo_FindPublicBySlug_Call) RunAndReturn(run func(context.Context, string) (*model.PublicStorefrontCatalog, error)) *MockIStorefrontRepo_FindPublicBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// SyncProducts provides a mock function with given fields: ctx, storefrontID, productsMap
func (_m *MockIStorefrontRepo) SyncProducts(ctx context.Context, storefrontID uuid.UUID, productsMap map[string]model.StorefrontProductMapItem) error {
	ret := _m.Called(ctx, storefrontID, productsMap)

	if len(ret) == 0 {
		panic("no return value specified for SyncProducts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]model.StorefrontProductMapItem) error); ok {
		r0 = rf(ctx, storefrontID, productsMap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIStorefrontRepo_SyncProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncProducts'
type MockIStorefrontRepo_SyncProducts_Call struct {
	*mock.Call
}

// SyncProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - storefrontID uuid.UUID
//   - productsMap map[string]model.StorefrontProductMapItem
func (_e *MockIStorefrontRepo_Expecter) SyncProducts(ctx interface{}, storefrontID interface{}, productsMap interface{}) *MockIStorefrontRepo_SyncProducts_Call {
	return &MockIStorefrontRepo_SyncProducts_Call{Call: _e.mock.On("SyncProducts", ctx, storefrontID, productsMap)}
}

func (_c *MockIStorefrontRepo_SyncProducts_Call) Run(run func(ctx context.Context, storefrontID uuid.UUID, productsMap map[string]model.StorefrontProductMapItem)) *MockIStorefrontRepo_SyncProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(map[string]model.StorefrontProductMapItem))
	})
	return _c
}

func (_c *MockIStorefrontRepo_SyncProducts_Call) Return(_a0 error) *MockIStorefrontRepo_SyncProducts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIStorefrontRepo_SyncProducts_Call) RunAndReturn(run func(context.Context, uuid.UUID, map[string]model.StorefrontProductMapItem) error) *MockIStorefrontRepo_SyncProducts_Call {
	_c.Call.Return(run)
	return _c
}

// TrackEvent provides a mock function with given fields: ctx, slug, eventType
func (_m *MockIStorefrontRepo) TrackEvent(ctx context.Context, slug string, eventType string) error {
	ret := _m.Called(ctx, slug, eventType)

	if len(ret) == 0 {
		panic("no return value specified for TrackEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, slug, eventType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIStorefrontRepo_TrackEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackEvent'
type MockIStorefrontRepo_TrackEvent_Call struct {
	*mock.Call
}

// TrackEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - eventType string
func (_e *MockIStorefrontRepo_Expecter) TrackEvent(ctx interface{}, slug interface{}, eventType interface{}) *MockIStorefrontRepo_TrackEvent_Call {
	return &MockIStorefrontRepo_TrackEvent_Call{Call: _e.mock.On("TrackEvent", ctx, slug, eventType)}
}

func (_c *MockIStorefrontRepo_TrackEvent_Call) Run(run func(ctx context.Context, slug string, eventType string)) *MockIStorefrontRepo_TrackEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIStorefrontRepo_TrackEvent_Call) Return(_a0 error) *MockIStorefrontRepo_TrackEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIStorefrontRepo_TrackEvent_Call) RunAndReturn(run func(context.Context, string, string) error) *MockIStorefrontRepo_TrackEvent_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, merchantID, req
func (_m *MockIStorefrontRepo) Update(ctx context.Context, merchantID uuid.UUID, req model.SaveStorefrontSettingsRequest) (*model.Storefront, error) {
	ret := _m.Called(ctx, merchantID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Storefront
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.SaveStorefrontSettingsRequest) (*model.Storefront, error)); ok {
		return rf(ctx, merchantID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.SaveStorefrontSettingsRequest) *model.Storefront); ok {
		r0 = rf(ctx, merchantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Storefront)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.SaveStorefrontSettingsRequest) error); ok {
		r1 = rf(ctx, merchantID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIStorefrontRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIStorefrontRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - req model.SaveStorefrontSettingsRequest
func (_e *MockIStorefrontRepo_Expecter) Update(ctx interface{}, merchantID interface{}, req interface{}) *MockIStorefrontRepo_Update_Call {
	return &MockIStorefrontRepo_Update_Call{Call: _e.mock.On("Update", ctx, merchantID, req)}
}

func (_c *MockIStorefrontRepo_Update_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, req model.SaveStorefrontSettingsRequest)) *MockIStorefrontRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.SaveStorefrontSettingsRequest))
	})
	return _c
}

func (_c *MockIStorefrontRepo_Update_Call) Return(_a0 *model.Storefront, _a1 error) *MockIStorefrontRepo_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIStorefrontRepo_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.SaveStorefrontSettingsRequest) (*model.Storefront, error)) *MockIStorefrontRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIStorefrontRepo creates a new instance of MockIStorefrontRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStorefrontRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStorefrontRepo {
	mock := &MockIStorefrontRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
