// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo

import (
	context "context"
	model "warungku-backend/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockIReportRepo is an autogenerated mock type for the IReportRepo type
type MockIReportRepo struct {
	mock.Mock
}

type MockIReportRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIReportRepo) EXPECT() *MockIReportRepo_Expecter {
	return &MockIReportRepo_Expecter{mock: &_m.Mock}
}

// FetchDailySummaries provides a mock function with given fields: ctx, merchantID, startDate, endDate
func (_m *MockIReportRepo) FetchDailySummaries(ctx context.Context, merchantID uuid.UUID, startDate string, endDate string) ([]model.DailySummary, error) {
	ret := _m.Called(ctx, merchantID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for FetchDailySummaries")
	}

	var r0 []model.DailySummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) ([]model.DailySummary, error)); ok {
		return rf(ctx, merchantID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) []model.DailySummary); ok {
		r0 = rf(ctx, merchantID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DailySummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, merchantID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIReportRepo_FetchDailySummaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDailySummaries'
type MockIReportRepo_FetchDailySummaries_Call struct {
	*mock.Call
}

// FetchDailySummaries is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - startDate string
//   - endDate string
func (_e *MockIReportRepo_Expecter) FetchDailySummaries(ctx interface{}, merchantID interface{}, startDate interface{}, endDate interface{}) *MockIReportRepo_FetchDailySummaries_Call {
	return &MockIReportRepo_FetchDailySummaries_Call{Call: _e.mock.On("FetchDailySummaries", ctx, merchantID, startDate, endDate)}
}

func (_c *MockIReportRepo_FetchDailySummaries_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, startDate string, endDate string)) *MockIReportRepo_FetchDailySummaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIReportRepo_FetchDailySummaries_Call) Return(_a0 []model.DailySummary, _a1 error) *MockIReportRepo_FetchDailySummaries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIReportRepo_FetchDailySummaries_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) ([]model.DailySummary, error)) *MockIReportRepo_FetchDailySummaries_Call {
	_c.Call.Return(run)
	return _c
}

// FetchHourlyTraffic provides a mock function with given fields: ctx, merchantID, date
func (_m *MockIReportRepo) FetchHourlyTraffic(ctx context.Context, merchantID uuid.UUID, date string) ([]model.HourlyTraffic, error) {
	ret := _m.Called(ctx, merchantID, date)

	if len(ret) == 0 {
		panic("no return value specified for FetchHourlyTraffic")
	}

	var r0 []model.HourlyTraffic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]model.HourlyTraffic, error)); ok {
		return rf(ctx, merchantID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []model.HourlyTraffic); ok {
		r0 = rf(ctx, merchantID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.HourlyTraffic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, merchantID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIReportRepo_FetchHourlyTraffic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchHourlyTraffic'
type MockIReportRepo_FetchHourlyTraffic_Call struct {
	*mock.Call
}

// FetchHourlyTraffic is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - date string
func (_e *MockIReportRepo_Expecter) FetchHourlyTraffic(ctx interface{}, merchantID interface{}, date interface{}) *MockIReportRepo_FetchHourlyTraffic_Call {
	return &MockIReportRepo_FetchHourlyTraffic_Call{Call: _e.mock.On("FetchHourlyTraffic", ctx, merchantID, date)}
}

func (_c *MockIReportRepo_FetchHourlyTraffic_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, date string)) *MockIReportRepo_FetchHourlyTraffic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockIReportRepo_FetchHourlyTraffic_Call) Return(_a0 []model.HourlyTraffic, _a1 error) *MockIReportRepo_FetchHourlyTraffic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIReportRepo_FetchHourlyTraffic_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) ([]model.HourlyTraffic, error)) *MockIReportRepo_FetchHourlyTraffic_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPaymentSummaries provides a mock function with given fields: ctx, merchantID, periodType, periodStart
func (_m *MockIReportRepo) FetchPaymentSummaries(ctx context.Context, merchantID uuid.UUID, periodType string, periodStart string) ([]model.PaymentMethodSummary, error) {
	ret := _m.Called(ctx, merchantID, periodType, periodStart)

	if len(ret) == 0 {
		panic("no return value specified for FetchPaymentSummaries")
	}

	var r0 []model.PaymentMethodSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) ([]model.PaymentMethodSummary, error)); ok {
		return rf(ctx, merchantID, periodType, periodStart)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) []model.PaymentMethodSummary); ok {
		r0 = rf(ctx, merchantID, periodType, periodStart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PaymentMethodSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, merchantID, periodType, periodStart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIReportRepo_FetchPaymentSummaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPaymentSummaries'
type MockIReportRepo_FetchPaymentSummaries_Call struct {
	*mock.Call
}

// FetchPaymentSummaries is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - periodType string
//   - periodStart string
func (_e *MockIReportRepo_Expecter) FetchPaymentSummaries(ctx interface{}, merchantID interface{}, periodType interface{}, periodStart interface{}) *MockIReportRepo_FetchPaymentSummaries_Call {
	return &MockIReportRepo_FetchPaymentSummaries_Call{Call: _e.mock.On("FetchPaymentSummaries", ctx, merchantID, periodType, periodStart)}
}

func (_c *MockIReportRepo_FetchPaymentSummaries_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, periodType string, periodStart string)) *MockIReportRepo_FetchPaymentSummaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIReportRepo_FetchPaymentSummaries_Call) Return(_a0 []model.PaymentMethodSummary, _a1 error) *MockIReportRepo_FetchPaymentSummaries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIReportRepo_FetchPaymentSummaries_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) ([]model.PaymentMethodSummary, error)) *MockIReportRepo_FetchPaymentSummaries_Call {
	_c.Call.Return(run)
	return _c
}

// FetchProductSales provides a mock function with given fields: ctx, merchantID, periodType, periodStart
func (_m *MockIReportRepo) FetchProductSales(ctx context.Context, merchantID uuid.UUID, periodType string, periodStart string) ([]model.ProductSalesSummary, error) {
	ret := _m.Called(ctx, merchantID, periodType, periodStart)

	if len(ret) == 0 {
		panic("no return value specified for FetchProductSales")
	}

	var r0 []model.ProductSalesSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) ([]model.ProductSalesSummary, error)); ok {
		return rf(ctx, merchantID, periodType, periodStart)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) []model.ProductSalesSummary); ok {
		r0 = rf(ctx, merchantID, periodType, periodStart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProductSalesSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, merchantID, periodType, periodStart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIReportRepo_FetchProductSales_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchProductSales'
type MockIReportRepo_FetchProductSales_Call struct {
	*mock.Call
}

// FetchProductSales is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - periodType string
//   - periodStart string
func (_e *MockIReportRepo_Expecter) FetchProductSales(ctx interface{}, merchantID interface{}, periodType interface{}, periodStart interface{}) *MockIReportRepo_FetchProductSales_Call {
	return &MockIReportRepo_FetchProductSales_Call{Call: _e.mock.On("FetchProductSales", ctx, merchantID, periodType, periodStart)}
}

func (_c *MockIReportRepo_FetchProductSales_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, periodType string, periodStart string)) *MockIReportRepo_FetchProductSales_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIReportRepo_FetchProductSales_Call) Return(_a0 []model.ProductSalesSummary, _a1 error) *MockIReportRepo_FetchProductSales_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIReportRepo_FetchProductSales_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) ([]model.ProductSalesSummary, error)) *MockIReportRepo_FetchProductSales_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAnalytics provides a mock function with given fields: ctx, merchantID, date
func (_m *MockIReportRepo) RefreshAnalytics(ctx context.Context, merchantID uuid.UUID, date string) error {
	ret := _m.Called(ctx, merchantID, date)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAnalytics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, merchantID, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIReportRepo_RefreshAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAnalytics'
type MockIReportRepo_RefreshAnalytics_Call struct {
	*mock.Call
}

// RefreshAnalytics is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - date string
func (_e *MockIReportRepo_Expecter) RefreshAnalytics(ctx interface{}, merchantID interface{}, date interface{}) *MockIReportRepo_RefreshAnalytics_Call {
	return &MockIReportRepo_RefreshAnalytics_Call{Call: _e.mock.On("RefreshAnalytics", ctx, merchantID, date)}
}

func (_c *MockIReportRepo_RefreshAnalytics_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, date string)) *MockIReportRepo_RefreshAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockIReportRepo_RefreshAnalytics_Call) Return(_a0 error) *MockIReportRepo_RefreshAnalytics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIReportRepo_RefreshAnalytics_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockIReportRepo_RefreshAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIReportRepo creates a new instance of MockIReportRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIReportRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIReportRepo {
	mock := &MockIReportRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
