// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo

import (
	context "context"
	model "warungku-backend/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockIPaymentRepo is an autogenerated mock type for the IPaymentRepo type
type MockIPaymentRepo struct {
	mock.Mock
}

type MockIPaymentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPaymentRepo) EXPECT() *MockIPaymentRepo_Expecter {
	return &MockIPaymentRepo_Expecter{mock: &_m.Mock}
}

// FindByOrderID provides a mock function with given fields: ctx, orderID
func (_m *MockIPaymentRepo) FindByOrderID(ctx context.Context, orderID uuid.UUID) (*model.Payment, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrderID")
	}

	var r0 *model.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Payment, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Payment); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPaymentRepo_FindByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrderID'
type MockIPaymentRepo_FindByOrderID_Call struct {
	*mock.Call
}

// FindByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockIPaymentRepo_Expecter) FindByOrderID(ctx interface{}, orderID interface{}) *MockIPaymentRepo_FindByOrderID_Call {
	return &MockIPaymentRepo_FindByOrderID_Call{Call: _e.mock.On("FindByOrderID", ctx, orderID)}
}

func (_c *MockIPaymentRepo_FindByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockIPaymentRepo_FindByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIPaymentRepo_FindByOrderID_Call) Return(_a0 *model.Payment, _a1 error) *MockIPaymentRepo_FindByOrderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPaymentRepo_FindByOrderID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Payment, error)) *MockIPaymentRepo_FindByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPaymentRepo creates a new instance of MockIPaymentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPaymentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPaymentRepo {
	mock := &MockIPaymentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
