// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo

import (
	context "context"
	model "warungku-backend/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockICategoryRepo is an autogenerated mock type for the ICategoryRepo type
type MockICategoryRepo struct {
	mock.Mock
}

type MockICategoryRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICategoryRepo) EXPECT() *MockICategoryRepo_Expecter {
	return &MockICategoryRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, merchantID, req
func (_m *MockICategoryRepo) Create(ctx context.Context, merchantID uuid.UUID, req model.CreateCategoryRequest) (*model.Category, error) {
	ret := _m.Called(ctx, merchantID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreateCategoryRequest) (*model.Category, error)); ok {
		return rf(ctx, merchantID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreateCategoryRequest) *model.Category); ok {
		r0 = rf(ctx, merchantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.CreateCategoryRequest) error); ok {
		r1 = rf(ctx, merchantID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICategoryRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockICategoryRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - req model.CreateCategoryRequest
func (_e *MockICategoryRepo_Expecter) Create(ctx interface{}, merchantID interface{}, req interface{}) *MockICategoryRepo_Create_Call {
	return &MockICategoryRepo_Create_Call{Call: _e.mock.On("Create", ctx, merchantID, req)}
}

func (_c *MockICategoryRepo_Create_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, req model.CreateCategoryRequest)) *MockICategoryRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.CreateCategoryRequest))
	})
	return _c
}

func (_c *MockICategoryRepo_Create_Call) Return(_a0 *model.Category, _a1 error) *MockICategoryRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICategoryRepo_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.CreateCategoryRequest) (*model.Category, error)) *MockICategoryRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, merchantID, id
func (_m *MockICategoryRepo) Delete(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, merchantID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, merchantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, merchantID, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICategoryRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockICategoryRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - id uuid.UUID
func (_e *MockICategoryRepo_Expecter) Delete(ctx interface{}, merchantID interface{}, id interface{}) *MockICategoryRepo_Delete_Call {
	return &MockICategoryRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, merchantID, id)}
}

func (_c *MockICategoryRepo_Delete_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID)) *MockICategoryRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockICategoryRepo_Delete_Call) Return(_a0 bool, _a1 error) *MockICategoryRepo_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICategoryRepo_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockICategoryRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByMerchant provides a mock function with given fields: ctx, merchantID
func (_m *MockICategoryRepo) FindAllByMerchant(ctx context.Context, merchantID uuid.UUID) ([]model.Category, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByMerchant")
	}

	var r0 []model.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Category, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Category); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICategoryRepo_FindAllByMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByMerchant'
type MockICategoryRepo_FindAllByMerchant_Call struct {
	*mock.Call
}

// FindAllByMerchant is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
func (_e *MockICategoryRepo_Expecter) FindAllByMerchant(ctx interface{}, merchantID interface{}) *MockICategoryRepo_FindAllByMerchant_Call {
	return &MockICategoryRepo_FindAllByMerchant_Call{Call: _e.mock.On("FindAllByMerchant", ctx, merchantID)}
}

func (_c *MockICategoryRepo_FindAllByMerchant_Call) Run(run func(ctx context.Context, merchantID uuid.UUID)) *MockICategoryRepo_FindAllByMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICategoryRepo_FindAllByMerchant_Call) Return(_a0 []model.Category, _a1 error) *MockICategoryRepo_FindAllByMerchant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICategoryRepo_FindAllByMerchant_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Category, error)) *MockICategoryRepo_FindAllByMerchant_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, merchantID, id
func (_m *MockICategoryRepo) FindByID(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*model.Category, error) {
	ret := _m.Called(ctx, merchantID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Category, error)); ok {
		return rf(ctx, merchantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Category); ok {
		r0 = rf(ctx, merchantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICategoryRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockICategoryRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - id uuid.UUID
func (_e *MockICategoryRepo_Expecter) FindByID(ctx interface{}, merchantID interface{}, id interface{}) *MockICategoryRepo_FindByID_Call {
	return &MockICategoryRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, merchantID, id)}
}

func (_c *MockICategoryRepo_FindByID_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID)) *MockICategoryRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockICategoryRepo_FindByID_Call) Return(_a0 *model.Category, _a1 error) *MockICategoryRepo_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICategoryRepo_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Category, error)) *MockICategoryRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockICategoryRepo) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICategoryRepo_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockICategoryRepo_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockICategoryRepo_Expecter) Ping(ctx interface{}) *MockICategoryRepo_Ping_Call {
	return &MockICategoryRepo_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockICategoryRepo_Ping_Call) Run(run func(ctx context.Context)) *MockICategoryRepo_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockICategoryRepo_Ping_Call) Return(_a0 error) *MockICategoryRepo_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICategoryRepo_Ping_Call) RunAndReturn(run func(context.Context) error) *MockICategoryRepo_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, merchantID, id, req
func (_m *MockICategoryRepo) Update(ctx context.Context, merchantID uuid.UUID, id uuid.UUID, req model.UpdateCategoryRequest) (*model.Category, error) {
	ret := _m.Called(ctx, merchantID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.UpdateCategoryRequest) (*model.Category, error)); ok {
		return rf(ctx, merchantID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.UpdateCategoryRequest) *model.Category); ok {
		r0 = rf(ctx, merchantID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, model.UpdateCategoryRequest) error); ok {
		r1 = rf(ctx, merchantID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICategoryRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockICategoryRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - id uuid.UUID
//   - req model.UpdateCategoryRequest
func (_e *MockICategoryRepo_Expecter) Update(ctx interface{}, merchantID interface{}, id interface{}, req interface{}) *MockICategoryRepo_Update_Call {
	return &MockICategoryRepo_Update_Call{Call: _e.mock.On("Update", ctx, merchantID, id, req)}
}

func (_c *MockICategoryRepo_Update_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID, req model.UpdateCategoryRequest)) *MockICategoryRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(model.UpdateCategoryRequest))
	})
	return _c
}

func (_c *MockICategoryRepo_Update_Call) Return(_a0 *model.Category, _a1 error) *MockICategoryRepo_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICategoryRepo_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, model.UpdateCategoryRequest) (*model.Category, error)) *MockICategoryRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICategoryRepo creates a new instance of MockICategoryRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICategoryRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICategoryRepo {
	mock := &MockICategoryRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
