// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo

import (
	context "context"
	model "warungku-backend/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockICustomerRepo is an autogenerated mock type for the ICustomerRepo type
type MockICustomerRepo struct {
	mock.Mock
}

type MockICustomerRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICustomerRepo) EXPECT() *MockICustomerRepo_Expecter {
	return &MockICustomerRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, merchantID, req
func (_m *MockICustomerRepo) Create(ctx context.Context, merchantID uuid.UUID, req model.CreateCustomerRequest) (*model.Customer, error) {
	ret := _m.Called(ctx, merchantID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreateCustomerRequest) (*model.Customer, error)); ok {
		return rf(ctx, merchantID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreateCustomerRequest) *model.Customer); ok {
		r0 = rf(ctx, merchantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.CreateCustomerRequest) error); ok {
		r1 = rf(ctx, merchantID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICustomerRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockICustomerRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - req model.CreateCustomerRequest
func (_e *MockICustomerRepo_Expecter) Create(ctx interface{}, merchantID interface{}, req interface{}) *MockICustomerRepo_Create_Call {
	return &MockICustomerRepo_Create_Call{Call: _e.mock.On("Create", ctx, merchantID, req)}
}

func (_c *MockICustomerRepo_Create_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, req model.CreateCustomerRequest)) *MockICustomerRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.CreateCustomerRequest))
	})
	return _c
}

func (_c *MockICustomerRepo_Create_Call) Return(_a0 *model.Customer, _a1 error) *MockICustomerRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICustomerRepo_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.CreateCustomerRequest) (*model.Customer, error)) *MockICustomerRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByMerchant provides a mock function with given fields: ctx, merchantID
func (_m *MockICustomerRepo) FindAllByMerchant(ctx context.Context, merchantID uuid.UUID) ([]model.Customer, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByMerchant")
	}

	var r0 []model.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Customer, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Customer); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICustomerRepo_FindAllByMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByMerchant'
type MockICustomerRepo_FindAllByMerchant_Call struct {
	*mock.Call
}

// FindAllByMerchant is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
func (_e *MockICustomerRepo_Expecter) FindAllByMerchant(ctx interface{}, merchantID interface{}) *MockICustomerRepo_FindAllByMerchant_Call {
	return &MockICustomerRepo_FindAllByMerchant_Call{Call: _e.mock.On("FindAllByMerchant", ctx, merchantID)}
}

func (_c *MockICustomerRepo_FindAllByMerchant_Call) Run(run func(ctx context.Context, merchantID uuid.UUID)) *MockICustomerRepo_FindAllByMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICustomerRepo_FindAllByMerchant_Call) Return(_a0 []model.Customer, _a1 error) *MockICustomerRepo_FindAllByMerchant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICustomerRepo_FindAllByMerchant_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Customer, error)) *MockICustomerRepo_FindAllByMerchant_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, merchantID, id
func (_m *MockICustomerRepo) FindByID(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*model.Customer, error) {
	ret := _m.Called(ctx, merchantID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Customer, error)); ok {
		return rf(ctx, merchantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Customer); ok {
		r0 = rf(ctx, merchantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICustomerRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockICustomerRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - id uuid.UUID
func (_e *MockICustomerRepo_Expecter) FindByID(ctx interface{}, merchantID interface{}, id interface{}) *MockICustomerRepo_FindByID_Call {
	return &MockICustomerRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, merchantID, id)}
}

func (_c *MockICustomerRepo_FindByID_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID)) *MockICustomerRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockICustomerRepo_FindByID_Call) Return(_a0 *model.Customer, _a1 error) *MockICustomerRepo_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICustomerRepo_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Customer, error)) *MockICustomerRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICustomerRepo creates a new instance of MockICustomerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICustomerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICustomerRepo {
	mock := &MockICustomerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
