// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo

import (
	context "context"
	model "warungku-backend/internal/model"

	mock "github.com/stretchr/testify/mock"

	repo "warungku-backend/internal/repo"

	uuid "github.com/google/uuid"
)

// MockIStockMovementRepo is an autogenerated mock type for the IStockMovementRepo type
type MockIStockMovementRepo struct {
	mock.Mock
}

type MockIStockMovementRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStockMovementRepo) EXPECT() *MockIStockMovementRepo_Expecter {
	return &MockIStockMovementRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sm
func (_m *MockIStockMovementRepo) Create(ctx context.Context, sm *model.StockMovement) error {
	ret := _m.Called(ctx, sm)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.StockMovement) error); ok {
		r0 = rf(ctx, sm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIStockMovementRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIStockMovementRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sm *model.StockMovement
func (_e *MockIStockMovementRepo_Expecter) Create(ctx interface{}, sm interface{}) *MockIStockMovementRepo_Create_Call {
	return &MockIStockMovementRepo_Create_Call{Call: _e.mock.On("Create", ctx, sm)}
}

func (_c *MockIStockMovementRepo_Create_Call) Run(run func(ctx context.Context, sm *model.StockMovement)) *MockIStockMovementRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.StockMovement))
	})
	return _c
}

func (_c *MockIStockMovementRepo_Create_Call) Return(_a0 error) *MockIStockMovementRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIStockMovementRepo_Create_Call) RunAndReturn(run func(context.Context, *model.StockMovement) error) *MockIStockMovementRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, merchantID, opts
func (_m *MockIStockMovementRepo) FindAll(ctx context.Context, merchantID uuid.UUID, opts repo.FindMovementOptions) ([]model.StockMovement, error) {
	ret := _m.Called(ctx, merchantID, opts)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.StockMovement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, repo.FindMovementOptions) ([]model.StockMovement, error)); ok {
		return rf(ctx, merchantID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, repo.FindMovementOptions) []model.StockMovement); ok {
		r0 = rf(ctx, merchantID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.StockMovement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, repo.FindMovementOptions) error); ok {
		r1 = rf(ctx, merchantID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIStockMovementRepo_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIStockMovementRepo_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - opts repo.FindMovementOptions
func (_e *MockIStockMovementRepo_Expecter) FindAll(ctx interface{}, merchantID interface{}, opts interface{}) *MockIStockMovementRepo_FindAll_Call {
	return &MockIStockMovementRepo_FindAll_Call{Call: _e.mock.On("FindAll", ctx, merchantID, opts)}
}

func (_c *MockIStockMovementRepo_FindAll_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, opts repo.FindMovementOptions)) *MockIStockMovementRepo_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(repo.FindMovementOptions))
	})
	return _c
}

func (_c *MockIStockMovementRepo_FindAll_Call) Return(_a0 []model.StockMovement, _a1 error) *MockIStockMovementRepo_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIStockMovementRepo_FindAll_Call) RunAndReturn(run func(context.Context, uuid.UUID, repo.FindMovementOptions) ([]model.StockMovement, error)) *MockIStockMovementRepo_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIStockMovementRepo creates a new instance of MockIStockMovementRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStockMovementRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStockMovementRepo {
	mock := &MockIStockMovementRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
