// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo

import (
	context "context"
	model "warungku-backend/internal/model"

	mock "github.com/stretchr/testify/mock"

	repo "warungku-backend/internal/repo"

	uuid "github.com/google/uuid"
)

// MockIAIRepo is an autogenerated mock type for the IAIRepo type
type MockIAIRepo struct {
	mock.Mock
}

type MockIAIRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAIRepo) EXPECT() *MockIAIRepo_Expecter {
	return &MockIAIRepo_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, merchantID, title
func (_m *MockIAIRepo) CreateSession(ctx context.Context, merchantID uuid.UUID, title string) (*model.AISession, error) {
	ret := _m.Called(ctx, merchantID, title)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *model.AISession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.AISession, error)); ok {
		return rf(ctx, merchantID, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.AISession); ok {
		r0 = rf(ctx, merchantID, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AISession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, merchantID, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAIRepo_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockIAIRepo_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - title string
func (_e *MockIAIRepo_Expecter) CreateSession(ctx interface{}, merchantID interface{}, title interface{}) *MockIAIRepo_CreateSession_Call {
	return &MockIAIRepo_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, merchantID, title)}
}

func (_c *MockIAIRepo_CreateSession_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, title string)) *MockIAIRepo_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockIAIRepo_CreateSession_Call) Return(_a0 *model.AISession, _a1 error) *MockIAIRepo_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAIRepo_CreateSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*model.AISession, error)) *MockIAIRepo_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields: ctx, merchantID, sessionID
func (_m *MockIAIRepo) DeleteSession(ctx context.Context, merchantID uuid.UUID, sessionID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, merchantID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, merchantID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, merchantID, sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAIRepo_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockIAIRepo_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - sessionID uuid.UUID
func (_e *MockIAIRepo_Expecter) DeleteSession(ctx interface{}, merchantID interface{}, sessionID interface{}) *MockIAIRepo_DeleteSession_Call {
	return &MockIAIRepo_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, merchantID, sessionID)}
}

func (_c *MockIAIRepo_DeleteSession_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, sessionID uuid.UUID)) *MockIAIRepo_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockIAIRepo_DeleteSession_Call) Return(_a0 bool, _a1 error) *MockIAIRepo_DeleteSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAIRepo_DeleteSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockIAIRepo_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// FindQueryLogs provides a mock function with given fields: ctx, merchantID, sessionID
func (_m *MockIAIRepo) FindQueryLogs(ctx context.Context, merchantID uuid.UUID, sessionID uuid.UUID) ([]model.AIQueryLog, error) {
	ret := _m.Called(ctx, merchantID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for FindQueryLogs")
	}

	var r0 []model.AIQueryLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]model.AIQueryLog, error)); ok {
		return rf(ctx, merchantID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []model.AIQueryLog); ok {
		r0 = rf(ctx, merchantID, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AIQueryLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAIRepo_FindQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindQueryLogs'
type MockIAIRepo_FindQueryLogs_Call struct {
	*mock.Call
}

// FindQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - sessionID uuid.UUID
func (_e *MockIAIRepo_Expecter) FindQueryLogs(ctx interface{}, merchantID interface{}, sessionID interface{}) *MockIAIRepo_FindQueryLogs_Call {
	return &MockIAIRepo_FindQueryLogs_Call{Call: _e.mock.On("FindQueryLogs", ctx, merchantID, sessionID)}
}

func (_c *MockIAIRepo_FindQueryLogs_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, sessionID uuid.UUID)) *MockIAIRepo_FindQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockIAIRepo_FindQueryLogs_Call) Return(_a0 []model.AIQueryLog, _a1 error) *MockIAIRepo_FindQueryLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAIRepo_FindQueryLogs_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]model.AIQueryLog, error)) *MockIAIRepo_FindQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessionByID provides a mock function with given fields: ctx, merchantID, sessionID
func (_m *MockIAIRepo) FindSessionByID(ctx context.Context, merchantID uuid.UUID, sessionID uuid.UUID) (*model.AISession, error) {
	ret := _m.Called(ctx, merchantID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for FindSessionByID")
	}

	var r0 *model.AISession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.AISession, error)); ok {
		return rf(ctx, merchantID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.AISession); ok {
		r0 = rf(ctx, merchantID, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AISession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAIRepo_FindSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessionByID'
type MockIAIRepo_FindSessionByID_Call struct {
	*mock.Call
}

// FindSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - sessionID uuid.UUID
func (_e *MockIAIRepo_Expecter) FindSessionByID(ctx interface{}, merchantID interface{}, sessionID interface{}) *MockIAIRepo_FindSessionByID_Call {
	return &MockIAIRepo_FindSessionByID_Call{Call: _e.mock.On("FindSessionByID", ctx, merchantID, sessionID)}
}

func (_c *MockIAIRepo_FindSessionByID_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, sessionID uuid.UUID)) *MockIAIRepo_FindSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockIAIRepo_FindSessionByID_Call) Return(_a0 *model.AISession, _a1 error) *MockIAIRepo_FindSessionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAIRepo_FindSessionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.AISession, error)) *MockIAIRepo_FindSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessions provides a mock function with given fields: ctx, merchantID
func (_m *MockIAIRepo) FindSessions(ctx context.Context, merchantID uuid.UUID) ([]model.AISession, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for FindSessions")
	}

	var r0 []model.AISession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.AISession, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.AISession); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AISession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAIRepo_FindSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessions'
type MockIAIRepo_FindSessions_Call struct {
	*mock.Call
}

// FindSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
func (_e *MockIAIRepo_Expecter) FindSessions(ctx interface{}, merchantID interface{}) *MockIAIRepo_FindSessions_Call {
	return &MockIAIRepo_FindSessions_Call{Call: _e.mock.On("FindSessions", ctx, merchantID)}
}

func (_c *MockIAIRepo_FindSessions_Call) Run(run func(ctx context.Context, merchantID uuid.UUID)) *MockIAIRepo_FindSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIAIRepo_FindSessions_Call) Return(_a0 []model.AISession, _a1 error) *MockIAIRepo_FindSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAIRepo_FindSessions_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.AISession, error)) *MockIAIRepo_FindSessions_Call {
	_c.Call.Return(run)
	return _c
}

// InsertFeedback provides a mock function with given fields: ctx, fb
func (_m *MockIAIRepo) InsertFeedback(ctx context.Context, fb *model.AIFeedback) error {
	ret := _m.Called(ctx, fb)

	if len(ret) == 0 {
		panic("no return value specified for InsertFeedback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AIFeedback) error); ok {
		r0 = rf(ctx, fb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAIRepo_InsertFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertFeedback'
type MockIAIRepo_InsertFeedback_Call struct {
	*mock.Call
}

// InsertFeedback is a helper method to define mock.On call
//   - ctx context.Context
//   - fb *model.AIFeedback
func (_e *MockIAIRepo_Expecter) InsertFeedback(ctx interface{}, fb interface{}) *MockIAIRepo_InsertFeedback_Call {
	return &MockIAIRepo_InsertFeedback_Call{Call: _e.mock.On("InsertFeedback", ctx, fb)}
}

func (_c *MockIAIRepo_InsertFeedback_Call) Run(run func(ctx context.Context, fb *model.AIFeedback)) *MockIAIRepo_InsertFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AIFeedback))
	})
	return _c
}

func (_c *MockIAIRepo_InsertFeedback_Call) Return(_a0 error) *MockIAIRepo_InsertFeedback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAIRepo_InsertFeedback_Call) RunAndReturn(run func(context.Context, *model.AIFeedback) error) *MockIAIRepo_InsertFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// InsertQueryLog provides a mock function with given fields: ctx, l
func (_m *MockIAIRepo) InsertQueryLog(ctx context.Context, l *model.AIQueryLog) error {
	ret := _m.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for InsertQueryLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AIQueryLog) error); ok {
		r0 = rf(ctx, l)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAIRepo_InsertQueryLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertQueryLog'
type MockIAIRepo_InsertQueryLog_Call struct {
	*mock.Call
}

// InsertQueryLog is a helper method to define mock.On call
//   - ctx context.Context
//   - l *model.AIQueryLog
func (_e *MockIAIRepo_Expecter) InsertQueryLog(ctx interface{}, l interface{}) *MockIAIRepo_InsertQueryLog_Call {
	return &MockIAIRepo_InsertQueryLog_Call{Call: _e.mock.On("InsertQueryLog", ctx, l)}
}

func (_c *MockIAIRepo_InsertQueryLog_Call) Run(run func(ctx context.Context, l *model.AIQueryLog)) *MockIAIRepo_InsertQueryLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AIQueryLog))
	})
	return _c
}

func (_c *MockIAIRepo_InsertQueryLog_Call) Return(_a0 error) *MockIAIRepo_InsertQueryLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAIRepo_InsertQueryLog_Call) RunAndReturn(run func(context.Context, *model.AIQueryLog) error) *MockIAIRepo_InsertQueryLog_Call {
	_c.Call.Return(run)
	return _c
}

// MatchKnowledge provides a mock function with given fields: ctx, merchantID, vectorStr, threshold, count
func (_m *MockIAIRepo) MatchKnowledge(ctx context.Context, merchantID uuid.UUID, vectorStr string, threshold float64, count int) ([]repo.MatchedDocument, error) {
	ret := _m.Called(ctx, merchantID, vectorStr, threshold, count)

	if len(ret) == 0 {
		panic("no return value specified for MatchKnowledge")
	}

	var r0 []repo.MatchedDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, float64, int) ([]repo.MatchedDocument, error)); ok {
		return rf(ctx, merchantID, vectorStr, threshold, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, float64, int) []repo.MatchedDocument); ok {
		r0 = rf(ctx, merchantID, vectorStr, threshold, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.MatchedDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, float64, int) error); ok {
		r1 = rf(ctx, merchantID, vectorStr, threshold, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAIRepo_MatchKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MatchKnowledge'
type MockIAIRepo_MatchKnowledge_Call struct {
	*mock.Call
}

// MatchKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - vectorStr string
//   - threshold float64
//   - count int
func (_e *MockIAIRepo_Expecter) MatchKnowledge(ctx interface{}, merchantID interface{}, vectorStr interface{}, threshold interface{}, count interface{}) *MockIAIRepo_MatchKnowledge_Call {
	return &MockIAIRepo_MatchKnowledge_Call{Call: _e.mock.On("MatchKnowledge", ctx, merchantID, vectorStr, threshold, count)}
}

func (_c *MockIAIRepo_MatchKnowledge_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, vectorStr string, threshold float64, count int)) *MockIAIRepo_MatchKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(float64), args[4].(int))
	})
	return _c
}

func (_c *MockIAIRepo_MatchKnowledge_Call) Return(_a0 []repo.MatchedDocument, _a1 error) *MockIAIRepo_MatchKnowledge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAIRepo_MatchKnowledge_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, float64, int) ([]repo.MatchedDocument, error)) *MockIAIRepo_MatchKnowledge_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionLastActive provides a mock function with given fields: ctx, sessionID
func (_m *MockIAIRepo) UpdateSessionLastActive(ctx context.Context, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionLastActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAIRepo_UpdateSessionLastActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionLastActive'
type MockIAIRepo_UpdateSessionLastActive_Call struct {
	*mock.Call
}

// UpdateSessionLastActive is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockIAIRepo_Expecter) UpdateSessionLastActive(ctx interface{}, sessionID interface{}) *MockIAIRepo_UpdateSessionLastActive_Call {
	return &MockIAIRepo_UpdateSessionLastActive_Call{Call: _e.mock.On("UpdateSessionLastActive", ctx, sessionID)}
}

func (_c *MockIAIRepo_UpdateSessionLastActive_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockIAIRepo_UpdateSessionLastActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIAIRepo_UpdateSessionLastActive_Call) Return(_a0 error) *MockIAIRepo_UpdateSessionLastActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAIRepo_UpdateSessionLastActive_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIAIRepo_UpdateSessionLastActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAIRepo creates a new instance of MockIAIRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAIRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAIRepo {
	mock := &MockIAIRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
