// Code generated by ifacemaker; DO NOT EDIT.

package repo

import (
	"context"
	"warungku-backend/internal/model"

	"github.com/google/uuid"
)

// IAIRepo defines the AI repository interface.
type IAIRepo interface {
	FindSessions(ctx context.Context, merchantID uuid.UUID) ([]model.AISession, error)
	FindSessionByID(ctx context.Context, merchantID, sessionID uuid.UUID) (*model.AISession, error)
	CreateSession(ctx context.Context, merchantID uuid.UUID, title string) (*model.AISession, error)
	DeleteSession(ctx context.Context, merchantID, sessionID uuid.UUID) (bool, error)
	FindQueryLogs(ctx context.Context, merchantID, sessionID uuid.UUID) ([]model.AIQueryLog, error)
	InsertQueryLog(ctx context.Context, l *model.AIQueryLog) error
	UpdateSessionLastActive(ctx context.Context, sessionID uuid.UUID) error
	MatchKnowledge(ctx context.Context, merchantID uuid.UUID, vectorStr string, threshold float64, count int) ([]MatchedDocument, error)
	InsertFeedback(ctx context.Context, fb *model.AIFeedback) error
}
