// Code generated by ifacemaker; DO NOT EDIT.

package repo

import (
	"context"
	"warungku-backend/internal/model"

	"github.com/google/uuid"
)

// ICategoryRepo defines the category repository interface.
type ICategoryRepo interface {
	FindAllByMerchant(ctx context.Context, merchantID uuid.UUID) ([]model.Category, error)
	FindByID(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*model.Category, error)
	Create(ctx context.Context, merchantID uuid.UUID, req model.CreateCategoryRequest) (*model.Category, error)
	Update(ctx context.Context, merchantID uuid.UUID, id uuid.UUID, req model.UpdateCategoryRequest) (*model.Category, error)
	Delete(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (bool, error)
	Ping(ctx context.Context) error
}
