// Code generated by ifacemaker; DO NOT EDIT.

package repo

import (
	"context"
	"warungku-backend/internal/model"

	"github.com/google/uuid"
)

// ICustomerRepo defines the customer repository interface.
type ICustomerRepo interface {
	FindAllByMerchant(ctx context.Context, merchantID uuid.UUID) ([]model.Customer, error)
	FindByID(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*model.Customer, error)
	Create(ctx context.Context, merchantID uuid.UUID, req model.CreateCustomerRequest) (*model.Customer, error)
}
