// Code generated by ifacemaker; DO NOT EDIT.

package repo

import (
	"context"
	"warungku-backend/internal/model"

	"github.com/google/uuid"
)

// IOrderRepo defines the order repository interface.
type IOrderRepo interface {
	ExecuteAtomicCheckout(ctx context.Context, merchantID uuid.UUID, req model.CheckoutRequest) (*model.CheckoutResult, error)
	FindRecentOrders(ctx context.Context, merchantID uuid.UUID, limit int) ([]model.Order, error)
	MapPostgresError(err error) error
}
