// Code generated by ifacemaker; DO NOT EDIT.

package repo

import (
	"context"
	"warungku-backend/internal/model"

	"github.com/google/uuid"
)

// IPaymentRepo defines the payment repository interface.
type IPaymentRepo interface {
	FindByOrderID(ctx context.Context, orderID uuid.UUID) (*model.Payment, error)
}
