// Code generated by ifacemaker; DO NOT EDIT.

package repo

import (
	"context"
	"warungku-backend/internal/model"

	"github.com/google/uuid"
)

// IProductRepo defines the product repository interface.
type IProductRepo interface {
	FindAllByMerchant(ctx context.Context, merchantID uuid.UUID, opts FindProductOptions) ([]model.Product, error)
	FindByID(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*model.Product, error)
	Create(ctx context.Context, merchantID uuid.UUID, req model.CreateProductRequest) (*model.Product, error)
	Update(ctx context.Context, merchantID uuid.UUID, id uuid.UUID, req model.UpdateProductRequest) (*model.Product, error)
	Delete(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (bool, error)
	ToggleActive(ctx context.Context, merchantID uuid.UUID, id uuid.UUID, isActive bool) (bool, error)
	FetchSalesFrequency(ctx context.Context, merchantID uuid.UUID) (map[string]int, error)
}
