// Code generated by ifacemaker; DO NOT EDIT.

package repo

import (
	"context"
	"warungku-backend/internal/model"

	"github.com/google/uuid"
)

// IReportRepo defines the report repository interface.
type IReportRepo interface {
	RefreshAnalytics(ctx context.Context, merchantID uuid.UUID, date string) error
	FetchDailySummaries(ctx context.Context, merchantID uuid.UUID, startDate, endDate string) ([]model.DailySummary, error)
	FetchHourlyTraffic(ctx context.Context, merchantID uuid.UUID, date string) ([]model.HourlyTraffic, error)
	FetchProductSales(ctx context.Context, merchantID uuid.UUID, periodType, periodStart string) ([]model.ProductSalesSummary, error)
	FetchPaymentSummaries(ctx context.Context, merchantID uuid.UUID, periodType, periodStart string) ([]model.PaymentMethodSummary, error)
}
