// Code generated by ifacemaker; DO NOT EDIT.

package repo

import (
	"context"
	"warungku-backend/internal/model"

	"github.com/google/uuid"
)

// IStorefrontRepo defines the storefront repository interface.
type IStorefrontRepo interface {
	FindByMerchant(ctx context.Context, merchantID uuid.UUID) (*model.Storefront, error)
	CreateDefault(ctx context.Context, merchantID uuid.UUID, slug, displayName string) (*model.Storefront, error)
	Update(ctx context.Context, merchantID uuid.UUID, req model.SaveStorefrontSettingsRequest) (*model.Storefront, error)
	FindLinkedProducts(ctx context.Context, storefrontID uuid.UUID) ([]model.StorefrontProduct, error)
	SyncProducts(ctx context.Context, storefrontID uuid.UUID, productsMap map[string]model.StorefrontProductMapItem) error
	CheckSlugAvailable(ctx context.Context, merchantID uuid.UUID, slug string) (bool, error)
	TrackEvent(ctx context.Context, slug, eventType string) error
	FindPublicBySlug(ctx context.Context, slug string) (*model.PublicStorefrontCatalog, error)
	CreateOnlineOrder(ctx context.Context, slug string, req model.CreateOnlineOrderRequest) (*model.OnlineOrder, error)
}
