// Code generated by ifacemaker; DO NOT EDIT.

package repo

import (
	"context"
	"warungku-backend/internal/model"

	"github.com/google/uuid"
)

// IStockMovementRepo defines the stock movement repository interface.
type IStockMovementRepo interface {
	FindAll(ctx context.Context, merchantID uuid.UUID, opts FindMovementOptions) ([]model.StockMovement, error)
	Create(ctx context.Context, sm *model.StockMovement) error
}
